/**
 * hooks/useContract.js
 *
 * Returns initialized Web3 contract instances for both
 * MicroDons (Project) and Donation contracts.
 *
 * Depends on:
 *  - window.ethereum (MetaMask) being available (set up by Person A's useWallet.js)
 *  - .env variables:
 *      REACT_APP_PROJECT_CONTRACT=0x...
 *      REACT_APP_DONATION_CONTRACT=0x...
 *  - ABI JSONs in src/contracts/ (generated by Truffle after migration)
 */

import { useState, useEffect, useCallback } from "react";
import Web3 from "web3";

// ABIs are auto-generated by Truffle into src/contracts/
// Adjust paths if Person A moves them elsewhere
let MicroDonsABI, DonationABI;
try {
  MicroDonsABI = require("../contracts/MicroDons.json");
} catch {
  MicroDonsABI = null;
}
try {
  DonationABI = require("../contracts/Donation.json");
} catch {
  DonationABI = null;
}

/**
 * @returns {{ projectContract, donationContract, web3, account, loading, error }}
 */
export function useContract() {
  const [web3, setWeb3] = useState(null);
  const [account, setAccount] = useState("");
  const [projectContract, setProjectContract] = useState(null);
  const [donationContract, setDonationContract] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  const init = useCallback(async () => {
    try {
      if (!window.ethereum) {
        throw new Error("MetaMask not detected. Please install MetaMask.");
      }

      const _web3 = new Web3(window.ethereum);
      await window.ethereum.request({ method: "eth_requestAccounts" });
      const accounts = await _web3.eth.getAccounts();
      const networkId = await _web3.eth.net.getId();

      setWeb3(_web3);
      setAccount(accounts[0]);

      // ── Project contract (Person A's MicroDons) ──
      let _projectContract = null;
      if (MicroDonsABI) {
        const projectNetwork = MicroDonsABI.networks?.[networkId];
        const projectAddress =
          projectNetwork?.address ||
          process.env.REACT_APP_PROJECT_CONTRACT;

        if (projectAddress) {
          _projectContract = new _web3.eth.Contract(
            MicroDonsABI.abi,
            projectAddress
          );
        }
      }

      // ── Donation contract ──
      let _donationContract = null;
      if (DonationABI) {
        const donationNetwork = DonationABI.networks?.[networkId];
        const donationAddress =
          donationNetwork?.address ||
          process.env.REACT_APP_DONATION_CONTRACT;

        if (donationAddress) {
          _donationContract = new _web3.eth.Contract(
            DonationABI.abi,
            donationAddress
          );
        }
      }

      if (!_projectContract)
        console.warn("⚠️ Project contract not found on this network.");
      if (!_donationContract)
        console.warn("⚠️ Donation contract not found on this network.");

      setProjectContract(_projectContract);
      setDonationContract(_donationContract);
    } catch (err) {
      console.error("useContract init error:", err);
      setError(err.message || "Failed to connect contracts");
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    init();

    // Re-init on account or network change
    if (window.ethereum) {
      window.ethereum.on("accountsChanged", init);
      window.ethereum.on("chainChanged", () => window.location.reload());
    }
    return () => {
      if (window.ethereum) {
        window.ethereum.removeListener("accountsChanged", init);
      }
    };
  }, [init]);

  return { projectContract, donationContract, web3, account, loading, error };
}

export default useContract;
